# import_modules.py
import os

def dynamic_import_modules():
    app_dir = os.path.join(os.path.dirname(__file__), 'app')
    import_modules_path = os.path.join(os.path.dirname(__file__), 'dynamic_import_modules.py')

    try:
        with open(import_modules_path, 'w') as f:
            f.write("# This file is auto-generated by dynamic_import_modules.py\n")
            f.write("import sys\n")
            f.write("sys.path.append(os.path.join(os.path.dirname(__file__), 'app'))\n\n")

            for root, dirs, files in os.walk(app_dir):
                for file in files:
                    if file.startswith('sys_') and file.endswith('.py'):
                        module_name = file[:-3]  # Remove .py extension
                        f.write(f"from {module_name} import *\n")

            print(f"Generated imports in {import_modules_path}")
    except Exception as e:
        print(f"An error occurred while generating imports: {e}")

if __name__ == "__main__":
    dynamic_import_modules()

