# generate_dynamic_imports.py
import os

def generate_dynamic_imports():
    app_dir = os.path.join(os.path.dirname(__file__), 'app')
    dynamic_imports_path = os.path.join(os.path.dirname(__file__), 'dynamic_imports.py')

    with open(dynamic_imports_path, 'w') as f:
        f.write("# This file is auto-generated by generate_dynamic_imports.py\n")
        f.write("import sys\n")
        f.write("sys.path.append(os.path.join(os.path.dirname(__file__), 'app'))\n\n")

        for root, dirs, files in os.walk(app_dir):
            for file in files:
                if file.startswith('sys_') and file.endswith('.py'):
                    module_name = file[:-3]  # Remove .py extension
                    f.write(f"from {module_name} import *\n")

    print(f"Generated dynamic imports in {dynamic_imports_path}")

if __name__ == "__main__":
    generate_dynamic_imports()
